## Начало численной лин алгебры

### Нахождение наибольшего собственного значения

В этом разделе мы рассмотрим некоторые методы, которые могут быть использованы для приближенного вычисления собственных значений матрицы A. Хотя для небольших матриц возможно найти точные собственные значения, этот подход оказывается нереалистичным для больших матриц.

Во многих вводных учебниках приводится прямой способ вычисления собственных значений квадратной матрицы A размером n × n путем нахождения корней связанного n-го степенного полинома, известного как характеристический полином. Например, предположим, что A - матрица размером 2 × 2.


$$
\begin{equation}
A = \left[ \begin{array}{rr} a & b  \\ c & d \end{array}\right]
\end{equation}
$$

Собственные значения A являются решениями квадратного уравнения $\lambda^2 - (a+d)\lambda + ad-bc = 0$, которое может быть явно записано через a, b, c и d с использованием формулы дискреминанта. Проблема с большими матрицами заключается в том, что полином будет высокой степени, и корни не могут быть легко найдены по формуле.

Алгоритмы, которые мы рассматриваем в этом разделе, являются итерационными методами. Они генерируют последовательность векторов $\{X^{(1)}, X^{(2)}, X^{(3)}, ... \}$, которые приближаются к истинному собственному вектору матрицы. Приближенное значение соответствующего собственного значения может быть вычислено путем умножения приближенного собственного вектора на матрицу A.

### Метод степеней

Метод генерирует последовательность векторов путем многократного умножения на матрицу. При выполнении определенных условий последовательность векторов приближается к собственному вектору, соответствующему собственному значению, которое имеет наибольшую абсолютную величину.

Для простейшего объяснения предположим, что A - матрица размером n × n, диагонализуемая с собственными векторами $\{V_1, V_2, ... V_n\}$, и $\lambda_1$ - собственное значение A с наибольшей по модулю величиной. Для начала работы метода степеней мы выбираем любой ненулевой вектор и обозначаем его $X^{(0)}$. Мы можем выразить $X^{(0)}$ как линейную комбинацию собственных векторов, так как они образуют базис в $\mathbb{R}^n$.

$$
\begin{equation}
X^{(0)} = c_1V_1 + c_2V_2 + ... c_nV_n
\end{equation}
$$

Затем мы формируем последовательность векторов $X^{(1)}$, $X^{(2)}$, $X^{(3)}$, ..., задавая $X^{(m)}= AX^{(m-1)}$. Каждый из этих векторов также может быть выражен через собственные векторы:

$$
\begin{align*}
X^{(1)} = AX^{(0)} & = c_1AV_1 + c_2AV_2 + ... c_nAV_n \\
                   & = c_1\lambda_1V_1 + c_2\lambda_2V_2 + ... c_n\lambda_nV_n \\
X^{(2)} = AX^{(1)} & = c_1\lambda_1AV_1 + c_2\lambda_2AV_2 + ... c_n\lambda_nAV_n \\
                   & = c_1\lambda_1^2V_1 + c_2\lambda_2^2V_2 + ... c_n\lambda_n^2V_n \\
                   & \vdots \\
X^{(m)} = AX^{(m-1)} & = c_1\lambda_1^{m-1}AV_1 + c_2\lambda_2^{m-1}AV_2 + ... c_n\lambda_n^{m-1}AV_n \\
                   & = c_1\lambda_1^mV_1 + c_2\lambda_2^mV_2 + ... c_n\lambda_n^mV_n
\end{align*}
$$

Затем в выражении для $X^{(m)}$ мы можем вынести множитель $\lambda_1^m$, чтобы понять, что происходит, когда $m$ становится большим.

$$
\begin{equation}
X^{(m)} =  \lambda_1^m\left(c_1V_1 + c_2\left(\frac{\lambda_2}{\lambda_1}\right)^mV_2 + ... c_n\left(\frac{\lambda_n}{\lambda_1}\right)^mV_n\right)
\end{equation}
$$

Если $|\lambda_1| > |\lambda_i|$ для всех $i\neq 1$, то $|\lambda_i/\lambda_1|< 1$ и $(\lambda_i/\lambda_1)^m$ будет стремиться к нулю, когда $m$ становится большим. Это означает, что если мы многократно умножаем вектор на матрицу $A$, то в конечном итоге мы получим вектор, близкий по направлению к собственному вектору, соответствующему $\lambda_1$.


Давайте продемонстрируем вычисление на данной здесь матрице, прежде чем обсудим метод далее.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr} -2 & 6 & 2 & -8 \\ -6 & 0 & 12 & 12 \\ -6 & 0 & 12 & 12 \\ -10 & 3 & 7 & 14 \end{array}\right]
\end{equation}
$$

Для практической целесообразности обычно масштабируют векторы в последовательности до единичной длины при применении метода степеней. Если векторы в последовательности не масштабируют, их величины будут увеличиваться, если $\lambda_1>1$, или убывать, если $\lambda_1<1$. Поскольку все компоненты векторов делятся на один и тот же коэффициент при масштабировании вектора, этот шаг не изменяет конечное поведение последовательности. Масштабированная последовательность векторов все равно приближается к направлению собственного вектора.

Мы выбираем произвольный $X^{(0)}$ и вычисляем $X^{(20)}$ с использованием следующего правила.
$$
\begin{equation}
X^{(m)}=\frac{AX^{(m-1)}}{||AX^{(m-1)}||}
\end{equation}
$$

In [1]:
import numpy as np
import numpy.linalg as linalg

In [2]:
A = np.array([[-2, 6, 2, -8],
              [-6, 0, 12, 12],
              [-6, 0, 12, 12],
              [-10, 3, 7, 14]])
X = np.array([1, 0, 0, 0])[:, None]

for _ in range(20):
    X = (A @ X) / linalg.norm(A @ X)

ans = np.array([
    [ 1.57532321e-12],
    [-5.77350269e-01],
    [-5.77350269e-01],
    [-5.77350269e-01]])
np.isclose(X, ans).all()

True

Если $X$ - собственный вектор матрицы A с единичной длиной, то $|AX| = |\lambda_1X| = |\lambda_1|$.  Значит мы аппроксимируем собственное значение $|\lambda_1|$ с помощью $|AX|$.

In [3]:
linalg.norm(A @ X)

24.000000000020005

Похоже, что 24 - это приближенная оценка для $\lambda_1$. Чтобы убедиться в правильности наших расчетов, мы можем сравнить $AX$ c $\lambda_1X$.

In [4]:
A@X - 24*X

array([[-4.09561274e-11],
       [-9.45021839e-12],
       [-9.45021839e-12],
       [-1.57509561e-11]])

Действительно, разность $AX−24X$ небольшая. Заметим, что в этом случае мы можем даже выполнить вычисления с использованием целочисленного умножения. Обратите внимание, что у $X$ первый элемент равен 0, а остальные элементы равны между собой. Если мы установим эти элементы в 1, результат легко вычислить даже без использования компьютера. (Помните, что мы можем изменить масштаб собственного вектора, и он все равно останется собственным вектором.)

$$
\begin{equation}
AX = \left[ \begin{array}{rrrr} -2 & 6 & 2 & -8 \\ -6 & 0 & 12 & 12 \\ -6 & 0 & 12 & 12 \\ -10 & 3 & 7 & 14 \end{array}\right]
\left[ \begin{array}{r} 0 \\ 1\\ 1 \\ 1 \end{array}\right] =
\left[ \begin{array}{r} 0 \\ 24\\ 24 \\ 24 \end{array}\right] = 24X
\end{equation}
$$

На практике нам часто неизвестно, сколько итераций потребуется для получения хорошего приближения собственного вектора. Вместо этого мы должны указать условие, при котором мы будем удовлетворены приближением, и завершить итерацию.  
Например, $||AX^{(m)}||\approx \lambda_1$ и $AX^{(m)}\approx \lambda_1X^{(m)}$ мы можем требовать $AX^{(m)} - ||AX^{(m)}||X^{(m)} < \epsilon$ для маленьких чисел $\epsilon$.  Это условие гарантирует, что $X_{(m)}$ ведет себя примерно как собственный вектор. Также лучше включить в код ограничение на количество итераций. Это гарантирует, что вычисление в конечном итоге завершится, даже если удовлетворительный результат еще не достигнут.

In [5]:

TOLERANCE = 1e-4
MAX_ITERATIONS = 100

iter = 0
X = np.array([1, 0, 0, 0])[:, None] # начальное приближение (какое-то)
Y = A @ X
difference = Y - linalg.norm(Y)*X
while (iter < MAX_ITERATIONS and linalg.norm(difference) > TOLERANCE):
    X = Y / linalg.norm(Y)
    Y = A@X
    difference = Y - linalg.norm(Y) * X
    iter += 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue is approximately:")
print(linalg.norm(Y),'\n')
print("Magnitude of the difference is:")
print(linalg.norm(difference))


Eigenvector is approximately:
[[ 1.65181395e-06]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]] 

Magnitude of the eigenvalue is approximately:
24.000020980823063 

Magnitude of the difference is:
4.328470441185797e-05


На практике более распространенным условием является требование $||X^{(m)} - X^{(m-1})|| < \epsilon$ для заданного $\epsilon$. Это условие требует лишь того, чтобы векторы в последовательности становились ближе друг к другу, а не обязательно приближались к собственному вектору.

In [6]:
X = np.array([1, 0, 0, 0])[:, None]
TOLERANCE = 1e-4
MAX_ITERATIONS = 100

#перепишите код выше с условием на разницу норм векторов X_m и X_{m-1}
iter = 0
prev_X = np.zeros_like(X)
while iter < MAX_ITERATIONS and linalg.norm(X - prev_X) > TOLERANCE:
    prev_X = X
    Y = A @ X
    X = Y / linalg.norm(Y)
    iter += 1

print("Eigenvector is approximately:")
print(X,'\n')
print("Magnitude of the eigenvalue is approximately:")
print(linalg.norm(Y),'\n')
print("Magnitude of the difference is:")
print(linalg.norm(difference))

Eigenvector is approximately:
[[ 2.64294012e-05]
 [-5.77350269e-01]
 [-5.77350269e-01]
 [-5.77350269e-01]] 

Magnitude of the eigenvalue is approximately:
24.000122026538186 

Magnitude of the difference is:
4.328470441185797e-05


### Метод степеней: преимущества и недостатки

Хотя метод степеней легко понять и применить, у него есть недостатки. Самый очевидный недостаток заключается в том, что метод применим только к наибольшему собственному значению. Это не является серьезным недостатком, поскольку в большинстве приложений требуется лишь приближенное значение наибольшего собственного значения. Однако можно легко модифицировать метод для приближенного вычисления других собственных значений.

Более существенным недостатком является медленная сходимость последовательности в некоторых случаях. Например, мы можем наблюдать, если $|\lambda_1|$ близко к $|\lambda_2|$, тогда $|\lambda_1/\lambda_2|^m$ стремиться к нулю медленно.  Степенной метод может несойтись, если $|\lambda_1| = |\lambda_2|$, то есть когда $\lambda_1 = -\lambda_2$, или когда $\lambda_1$ и $\lambda_2$ комплексно сопряженная пара.  Плюс начальное приближение $X_0$ не должен иметь координаты сильно близкие к нулю.

**Задание 1:** Напишите функцию для поиска наибольшего собственного значения по модулю.

In [7]:
def largest_eigen_value(matrix: np.ndarray, tolerance: float=1e-4, max_iter: int=100) -> tuple:
    X = np.random.rand(matrix.shape[0], 1)
    X /= linalg.norm(X)

    iter = 0
    prev_X = np.zeros_like(X)
    while iter < max_iter and linalg.norm(X - prev_X) > tolerance:
        prev_X = X
        Y = matrix @ X
        X = Y / linalg.norm(Y)
        iter += 1

    eigenvalue = (X.T @ matrix @ X / (X.T @ X))[0][0]

    return eigenvalue, X

A = np.array([[9,-1,-3],[0,6,0],[-6,3,6]])
largest_e_val, _ = largest_eigen_value(A)
np.isclose(largest_e_val, 12)

True

## Стохастические матрицы

Стохастическая матрица – это квадратная матрица, элементы которой являются неотрицательными и такими, что сумма элементов каждой строки/столбца равна единице. Эта особенность делает стохастические матрицы ключевыми в теории вероятностей и марковских процессах. Матрица $P$ размерности $n \times n$ считается стохастической, если выполняется условие:

$
\sum_{j=1}^{n} P_{ij} = 1 \quad \text{для } i = 1, 2, \ldots, n
$

где $P_{ij}$ - элемент матрицы в i-й строке и j-м столбце. Эта характеристика связана с вероятностной интерпретацией: элемент $P_{ij}$ может рассматриваться как вероятность перехода из состояния $i$ в состояние $j$ в марковском процессе. Такие матрицы широко применяются в моделировании случайных процессов и анализе систем, где случайные переходы между состояниями играют важную роль.

Дальше нам понадобятся два факта о стохастических матрицах (в подпунктах представлено их доказательно, но оно нам не понадобиться в дальнейшем)

- 1 является собственным значением для любой стохастической матрицы
    - проверьте, что у $A$ и у $A^T$ одинаковые собственные значения
    - проверьте является ли вектор из всех единиц собственным вектором для собственного значения 1

- для любого собственного значения стохастической матрицы $\lambda$ выполнено $|\lambda| \leq 1$
    - Предположим, что $Ax = \lambda x$ для некоторого $\lambda > 1$. Поскольку строки матрицы $A$ неотрицательны и суммируются до 1, каждый элемент вектора $Ax$ представляет собой выпуклую комбинацию компонентов вектора $x$, которая не может быть больше, чем $x_{\text{max}}$, наибольшая компонента вектора $x$. С другой стороны, по меньшей мере один элемент $\lambda x$ больше $x_{\text{max}}$, что доказывает, что $\lambda > 1$ невозможно. В итоге данное утверждение демонстрирует, что если $Ax = \lambda x$ для некоторого $\lambda > 1$, то это приводит к противоречию, поскольку компоненты $\lambda x$ не могут превышать максимальную компоненту $x$. Следовательно, предположение $\lambda > 1$ доказано невозможным.


## PageRank

PageRank (разработанный Ларри Пейджем и Сергеем Брином) произвел революцию в веб-поиске, создав ранжированный список веб-страниц на основе базовых возможностей подключения к Интернету. Алгоритм PageRank основан на идеальном случайном веб-серфере, который, зайдя на страницу, переходит на следующую страницу, нажав на ссылку. Пользователь имеет равную вероятность перейти по любой ссылке на странице и, перейдя на страницу без ссылок, имеет равную вероятность перейти на любую другую страницу, введя ее URL. Кроме того, пользователь может иногда выбрать ввод случайного URL-адреса вместо перехода по ссылкам на странице. PageRank - это ранжированный порядок страниц от наиболее вероятной до наименее вероятной страницы, которую будет просматривать пользователь.

## PageRank как задача линейной алгебры

Давайте представим микроинтернет, содержащий всего 6 веб-сайтов (Avocado, Bullseye, Cat Babel, Dromeda, eTings, and FaceSpace). Каждый веб-сайт ссылается на некоторые другие, и это формирует сеть, как показано на рисунке,

![image info](./internet.png)

Принцип разработки PageRank заключается в том, что на важные веб-сайты будут ссылаться другие важные веб-сайты. Этот рекурсивный принцип ляжет в основу нашего мышления.

Представьте, что в нашем микроинтернете есть 100 прокрастинирующих пользователей, каждый из которых одновременно просматривает один веб-сайт. Каждую минуту пользователи переходят по ссылке на своем веб-сайте на другой сайт в микроинтернете. Через некоторое время на веб-сайты, на которые больше всего ссылок, будет заходить больше посетителей, и в долгосрочной перспективе каждую минуту на каждый посетитель, покидающий веб-сайт, будет заходить другой, сохраняя общее количество посетителей на каждом веб-сайте постоянным. PageRank - это просто ранжирование веб-сайтов по количеству размещенных на них частей в конце этого процесса.

Мы представляем количество просмотров на каждом веб-сайте с помощью вектора,
$$\mathbf{r} = \begin{bmatrix} r_A \\ r_B \\ r_C \\ r_D \\ r_E \\ r_F \end{bmatrix}$$

И скажем, что количество путей на каждом веб-сайте в минуту $i+1$ связано с количеством путей в минуту $i$ с помощью матричного преобразования

$$ \mathbf{r}^{(i+1)} = L \,\mathbf{r}^{(i)}$$
с матрицей $L$ следующего вида
$$ L = \begin{bmatrix}
L_{A→A} & L_{B→A} & L_{C→A} & L_{D→A} & L_{E→A} & L_{F→A} \\
L_{A→B} & L_{B→B} & L_{C→B} & L_{D→B} & L_{E→B} & L_{F→B} \\
L_{A→C} & L_{B→C} & L_{C→C} & L_{D→C} & L_{E→C} & L_{F→C} \\
L_{A→D} & L_{B→D} & L_{C→D} & L_{D→D} & L_{E→D} & L_{F→D} \\
L_{A→E} & L_{B→E} & L_{C→E} & L_{D→E} & L_{E→E} & L_{F→E} \\
L_{A→F} & L_{B→F} & L_{C→F} & L_{D→F} & L_{E→F} & L_{F→F} \\
\end{bmatrix}
$$
где столбцы представляют вероятность перехода с веб-сайта на любой другой веб-сайт и суммируются в единицу.
Строки определяют, насколько вероятно, что вы перейдете на веб-сайт с любого другого веб-сайта, их величины необязательно суммируются в единицу.
Длительное поведение этой системы сводится к условию $ \mathbf{r}^{(i+1)} = \mathbf{r}^{(i)}$, можно опустить индексы и переписать это так:
$$ L \,\mathbf{r} = \mathbf{r}$$

In [8]:
# Замените символы ... на вероятность перейти из сайта FaceSpace в другие
L = np.array([[0,   1/2, 1/3, 0, 0,   0],
              [1/3, 0,   0,   0, 1/2, 0],
              [1/3, 1/2, 0,   1, 0,   1/2],
              [1/3, 0,   1/3, 0, 1/2, 1/2],
              [0,   0,   0,   0, 0,   0],
              [0,   0,   1/3, 0, 0,   0]])

В принципе, мы могли бы использовать библиотеку линейной алгебры, как показано ниже, для вычисления собственных значений и векторов. И это сработало бы для небольшой системы. Но это становится невозможным для больших систем. И поскольку мы заботимся только о главном собственном векторе (том, который имеет наибольшее собственное значение, которое в данном случае будет равно 1), мы можем использовать степенной метод, который будет лучше масштабироваться и быстрее для больших систем.

Используйте приведенный ниже код, чтобы просмотреть PageRank для этого микроинтернета.

In [9]:
eVals, eVecs = linalg.eig(L) # получить собс. значения и собс. вектора
order = np.absolute(eVals).argsort()[::-1] # отсортируем их по абс. значениям
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0] # пусть r это вектор соответствующий максимальному собственному значению
100 * np.real(r / np.sum(r)) # нормируем вектор, чтобы суммировался в 1, затем умножим на 100 прокрастинирующих пользователей

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

Из этого списка мы можем видеть количество прокрастинирующих пользователей, которые мы ожидаем найти на каждом веб-сайте через долгое время. Расположив их в порядке популярности (на основе этого показателя), PageRank этого микроинтернет составляет:

CatBabel, Dromeda, Avocado, FaceSpace, Bullseye, eTings

Возвращаясь к диаграмме микроинтернет, этого ли вы ожидали? Убедите себя, что на основе того, какие страницы кажутся важными, учитывая, какие другие ссылаются на них, это разумный рейтинг.

Примените степенной метод для матрицы $L$ и сравните полученный результат с результатом выше

In [10]:
e_val, e_vec = largest_eigen_value(L)
np.isclose(e_vec / linalg.norm(e_vec), r[:, None] / linalg.norm(r[:, None]), rtol=1e-3).all()

True

### Параметр затухания

Система, которую мы только что рассмотрели, сходилась достаточно быстро к правильному ответу.
Рассмотрим расширение нашего микро-интернета, где начинаются проблемы.

Предположим, что в микро-интернет добавлен новый сайт: Веб-сайт *Geoff*.
Этот сайт связан с *FaceSpace* и ссылается только на себя.


![Расширенный микро-интернет](./internet2.png "Расширенный микро-интернет")


Интуитивно понятно, что только *FaceSpace*, находящийся в нижней половине рейтинга страниц, ссылается на этот сайт среди двух других, поэтому мы можем ожидать, что у *Geoff* будет соответственно низкий рейтинг PageRank.

Постройте новую матрицу $L$ для расширенного микро-интернета и используйте степенной метод. Посмотрим, что произойдет...

In [11]:
# будем использовать переменную L2 для матрицы нового интернета
L2 = np.array([[0,   1/2, 1/3, 0, 0,   0, 0 ],
               [1/3, 0,   0,   0, 1/2, 0, 0 ],
               [1/3, 1/2, 0,   1, 0,   0, 0 ],
               [1/3, 0,   1/3, 0, 1/2, 0, 0 ],
               [0,   0,   0,   0, 0,   0, 0 ],
               [0,   0,   1/3, 0, 0,   1, 0 ],
               [0,   0,   0,   0, 0,   0, 1 ]])

In [12]:
e_val, e_vec = largest_eigen_value(L2)
e_vec

array([[2.12103714e-04],
       [8.27453483e-05],
       [4.19574029e-04],
       [2.46428467e-04],
       [0.00000000e+00],
       [9.91404440e-01],
       [1.30831751e-01]])

### Параметр затухания

Это не так хорошо! *Geoff* кажется привлекающим всё внимание в микро-интернете и, кажется, находится в верхней части рейтинга PageRank.
Это поведение можно понять, потому что, когда пользователь попадает на веб-сайт *Geoff*, он не может покинуть его, так как все ссылки ведут обратно к *Geoff*.

Чтобы справиться с этим, мы можем добавить небольшую вероятность того, что пользователь не будут следовать по ссылке на веб-странице, а вместо этого посетят веб-сайт на микро-интернете случайным образом.
Мы скажем, что вероятность того, что они перейдут по ссылке, равна $d$, и вероятность выбора случайного веб-сайта равна, следовательно, $1-d$.
Мы можем использовать новую матрицу, чтобы определить, на какие веб-сайты посещают пользователи каждую минуту.
$$ M = d \, L + \frac{1-d}{n} \, J $$
где $J$ - это матрица размером $n\times n$, в которой каждый элемент равен единице.

Если $d$ равно единице, у нас есть тот случай, который у нас был ранее, тогда как если $d$ равно нулю, мы всегда будем посещать случайную веб-страницу, и, следовательно, все веб-страницы будут равновероятными и равнозначными.

Чтобы эта модификация работала лучше всего, $1-d$ должно быть довольно маленьким, хотя мы не будем обсуждать, насколько именно маленьким. Давайте попробуем этот метод PageRank с этим расширением.

In [13]:
d = 0.7 # можете поиграть с этим параметром
M = d * L2 + (1 - d) / L2.shape[0] * np.ones_like(L2)
e_val, e_vec = largest_eigen_value(M)
e_vec

array([[0.27525338],
       [0.20009713],
       [0.44817464],
       [0.30467107],
       [0.10064549],
       [0.68390003],
       [0.33565307]])

### Параметр затухания

Это, конечно, лучше. PageRank предоставляет разумные значения пользователей, которые оказываются на каждой веб-странице.
Тем не менее этот метод все еще предсказывает, что у Джеффа есть высокий рейтинг веб-страницы.
Это можно рассматривать как следствие использования небольшой сети. Мы также можем обойти эту проблему, не учитывая ссылки на себя при создании матрицы $L$ (и если у веб-сайта нет исходящих ссылок, сделать его равномерно связанным со всеми веб-сайтами).
Мы не будем идти дальше по этому пути, поскольку это уже относится к улучшениям PageRank, а не к собственным задачам.

Теперь у вас есть хорошие знания о PageRank, и вы можете написать свой код для вычисления PageRank веб-сайта с тысячами записей.

In [14]:
def calc_pagerank(adj_matrix, dampler=0.8):
    """
    adj_matrix - матрица связи графа (1 если свзяь есть, 0 если связи нет)
    dampler - параметр затухания

    return:
        pagerank вектор, показывающий важность сайта
    """
    n = adj_matrix.shape[0]
    L = adj_matrix.copy().astype(np.float64)
    column_sums = L.sum(axis=0)
    column_sums[column_sums == 0] = 1
    L /= column_sums

    J = np.ones((n, n))
    M = dampler * L + (1 - dampler) / n * J
    _, e_vec = largest_eigen_value(M)
    return e_vec


test_internet = np.array([
    [0, 1, 1, 0, 1, 1, 1, 0, 1, 1],
    [1, 0, 0, 0, 1, 1, 0, 0, 1, 1],
    [1, 1, 0, 1, 1, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 1, 0],
    [1, 0, 1, 0, 1, 1, 1, 0, 1, 0],
    [0, 1, 1, 1, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 1, 0, 1, 1, 0, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1, 1, 0, 1, 0, 0]])

e_vec = calc_pagerank(test_internet)
sorted_internet = np.arange(len(test_internet))[np.argsort(e_vec.flatten())]
sorted_internet

array([6, 8, 1, 5, 2, 3, 7, 4, 9, 0])